version: '2'
services:

  pyload:
    image: writl/pyload
    container_name: pyload
    restart: always
    ports:
      - "9092:8000"
    networks:
      - nanoon
    environment:
      - PGID=$NANOON_GID
      - PUID=$NANOON_UID
      - TZ=Europe/Paris
    volumes:
     - $NANOON_FILESDIR/Downloads/:/opt/pyload/Downloads
     - $NANOON_CONFIGDIR/pyload/:/opt/pyload/pyload-config
    labels:
     - "traefik.frontend.rule=Host:$NANOON_DOWNLOAD"
     - "traefik.port=8000"
     - "traefik.enable=true"

networks:
  nanoon:
    external:
      name: traefik_nanoon

