version: '2'
services:

  htpcmanager:
    container_name: htpcmanager
    restart: always
    image: linuxserver/htpcmanager
    ports:
      - "8085:8085"
    networks:
      - nanoon
    environment:
      - PGID=$NANOON_GID
      - PUID=$NANOON_UID
      - TZ=Europe/Paris
    volumes:
     - $NANOON_CONFIGDIR/htpcmanager/:/config

  lazylibrarian:
    container_name: lazylibrarian
    restart: always
    image: linuxserver/lazylibrarian
    ports:
      - "5299:5299"
    networks:
      - nanoon
    environment:
      - PGID=$NANOON_GID
      - PUID=$NANOON_UID
      - TZ=Europe/Paris
    volumes:
     - $NANOON_FILESDIR/Transmission/:/downloads
     - $NANOON_FILESDIR/Books/:/books
     - $NANOON_CONFIGDIR/lazylibrarian/:/config
    labels:
     - "traefik.frontend.rule=Host:$NANOON_BOOK"
     - "traefik.port=5299"
     - "traefik.enable=true"

  mylar:
    container_name: mylar
    restart: always
    image: linuxserver/mylar
    ports:
      - "8090:8090"
    networks:
      - nanoon
    environment:
      - PGID=$NANOON_GID
      - PUID=$NANOON_UID
      - TZ=Europe/Paris
    volumes:
     - $NANOON_FILESDIR/Books/:/books
     - $NANOON_FILESDIR/Comics/:/comics
     - $NANOON_CONFIGDIR/mylar/:/config
    #labels:
     #- "traefik.frontend.rule=Host:comic.nesven.eu"
     #- "traefik.port=8090"
     #- "traefik.enable=true"

  ombi:
    container_name: ombi
    restart: always
    image: linuxserver/ombi
    ports:
      - "3579:3579"
    networks:
      - nanoon
    environment:
      - PGID=$NANOON_GID
      - PUID=$NANOON_UID
      - TZ=Europe/Paris
    volumes:
     - $NANOON_CONFIGDIR/ombi/:/config
    labels:
     - "traefik.frontend.rule=Host:$NANOON_MEDIA"
     - "traefik.port=3579"
     - "traefik.enable=true"


networks:
  nanoon:
    external:
      name: traefik_nanoon
