version: '2'
services:

  nextcloud:
    restart: always
    container_name: nextcloud
    image: nextcloud:15-fpm-alpine
    networks:
      - nanoon
    #ports:
    #  - 8889:80
    links:
      - db_nextcloud:db_nextcloud 
      - redis-nextcloud:redis
      - solr
    environment:
      - TZ=Europe/Paris
    volumes:
      - nextcloud:/var/www/html
      - $NANOON_CONFIGDIR/nextcloud/config.php:/var/www/html/config/config.php
      #- $NANOON_FILESDIR/Cloud/apps:/var/www/html/apps
      #- $NANOON_FILESDIR/Cloud/custom_apps:/var/www/html/custom_apps
      - $NANOON_FILESDIR/Cloud/data/:/data
      - $NANOON_FILESDIR/:/Files
    #labels:
    #  - "traefik.frontend.rule=Host:$NANOON_CLOUD"
    #  - "traefik.port=80"
    #  - "traefik.enable=true"


  cron:
    image: nextcloud:15-fpm-alpine
    container_name: cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - $NANOON_CONFIGDIR/nextcloud/config.php:/var/www/html/config/config.php
      #- $NANOON_CONFIGDIR/nextcloud/:/var/www/html/config
      #- $NANOON_FILESDIR/Cloud/apps:/var/www/html/apps
      #- $NANOON_FILESDIR/Cloud/custom_apps:/var/www/html/custom_apps
      - $NANOON_FILESDIR/Cloud/data/:/data
    links:
      - db_nextcloud
      - redis-nextcloud:redis
    depends_on:
      - nextcloud
    entrypoint: /cron.sh 
    networks:
     - nanoon

  nginx-nextcloud:
    image: nginx:alpine
    container_name: nginx-nextcloud
    restart: always
    networks:
      - nanoon 
    ports:
      - 8889:80
    volumes:
      - $NANOON_CONFIGDIR/nginx-nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html
      #- $NANOON_FILESDIR/Cloud/apps:/var/www/html/apps
      #- $NANOON_FILESDIR/Cloud/custom_apps:/var/www/html/custom_apps
      #- $NANOON_FILESDIR/Cloud/data/:/var/www/html/data
    depends_on: 
      - nextcloud
    labels:
     - "traefik.frontend.rule=Host:$NANOON_CLOUD"
     - "traefik.port=80"
     - "traefik.enable=true"

  db_nextcloud:
    restart: always
    image: mariadb
    container_name: db_nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nanoon
    environment:
      - MYSQL_ROOT_PASSWORD=dbpass 
      - MYSQL_DATABASE=nextcloud 
      - MYSQL_USER=nextcloud 
      - MYSQL_PASSWORD=dbpass
      - TZ=Europe/Paris
    volumes:
      - $NANOON_CONFIGDIR/db_nextcloud/datadir:/var/lib/mysql
  
  redis-nextcloud:
     restart: always
     container_name: redis-nextcloud
     image: redis:alpine
     networks:
      - nanoon
     environment:
      - TZ=Europe/Paris

  collabora:
    mem_limit: 384M
    restart: always
    container_name: collabora
    image: collabora/code
    networks:
      - nanoon
    ports:
      - "9980:9980"
    environment:
      - TZ=Europe/Paris
      - username=admin
      - password=S3cRet
    labels:
      - "traefik.frontend.rule=Host:$NANOON_OFFICE"
      - "traefik.port=9980"
      - "traefik.enable=true"
    volumes:
     - $NANOON_CONFIGDIR/collabora/loolwsd.xml:/etc/loolwsd/loolwsd.xml
    cap_add:
      - MKNOD


  solr:
    restart: always
    container_name: solr
    image: solr:6-alpine
    container_name: solr
    ports:
      - "8983:8983"
    networks:
      - nanoon
    volumes:
      - $NANOON_FILESDIR/Solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant

volumes:
    nextcloud:

networks:
  nanoon:
    external:
      name: traefik_nanoon

