version: '2'
services:

  rocketchat-mongo:
    image: mongo:3.4
    restart: always
    container_name: rocketchat-mongo
    command: mongod --smallfiles
    networks:
      - nanoon
    ports:
      - "27017:27017"
    environment:
      - TZ=Europe/Paris
    volumes:
      - $NANOON_CONFIGDIR/rocketchat-mongo/:/data/db

  rocketchat:
    #image: rocket.chat:0.62.0
    image: rocket.chat
    restart: always
    container_name: rocketchat
    ports:
      - "8097:3000"
    networks:
      - nanoon
    environment:
      - TZ=Europe/Paris
      - ROOT_URL=https://$NANOON_CHAT
      #- MONGO_URL=mongodb://192.168.1.60:27017
    links:
      - rocketchat-mongo:db
    labels:
     - "traefik.frontend.rule=Host:$NANOON_CHAT"
     - "traefik.port=3000"
     - "traefik.enable=true"

  taiga-postgres:
    container_name: taiga-postgres
    image: postgres:10
    restart: always
    networks:
      - nanoon
    environment:
      - TZ=Europe/Paris
      - POSTGRES_DB=taigadb 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=password
    volumes:
      - $NANOON_CONFIGDIR/taiga-postgres:/var/lib/postgresql/data

  taiga-redis:
    container_name: taiga-redis
    image: redis:3
    restart: always
    networks:
      - nanoon
    environment:
      - TZ=Europe/Paris

  taiga-rabbit:
    container_name: taiga-rabbit
    image: rabbitmq:3
    restart: always
    networks:
      - nanoon
    environment:
      - TZ=Europe/Paris

  taiga-celery:
    container_name: taiga-celery
    image: celery
    restart: always
    networks:
      - nanoon
    links:
      - taiga-rabbit:rabbit
    environment:
      - TZ=Europe/Paris

  taiga-events:
    container_name: taiga-events
    image: benhutchins/taiga-events
    restart: always
    networks:
      - nanoon
    links:
      - taiga-rabbit:rabbit
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.frontend.rule=Host:$NANOON_TAIGA;PathPrefixStrip:/events"
      - "traefik.port=8888"
      - "traefik.enable=true"

  taiga:
    container_name: taiga
    image: benhutchins/taiga
    restart: always
    networks:
      - nanoon
    ports:
      - 8089:80
    links:
      - taiga-rabbit:rabbit
      - taiga-redis:redis 
      - taiga-events:events 
      - taiga-postgres:postgres
    environment:
      - TZ=Europe/Paris
      - TAIGA_DB_NAME=taigadb
      - TAIGA_DB_HOST=postgres
      - TAIGA_DB_USER=postgres
      - TAIGA_DB_PASSWORD=password
      - TAIGA_HOSTNAME=$NANOON_TAIGA
      - TAIGA_SSL_BY_REVERSE_PROXY=True
      - RABBIT_PORT=5672
      - REDIS_PORT=6379
    volumes:
      - $NANOON_FILESDIR/Taiga-media:/usr/src/taiga-back/media 
      - $NANOON_CONFIGDIR/taiga:/taiga:ro
      - $NANOON_CONFIGDIR/taiga/celery.py:/usr/src/taiga-back/settings/celery.py:ro
    labels:
      - "traefik.frontend.rule=Host:$NANOON_TAIGA"
      - "traefik.port=80"
      - "traefik.enable=true"

networks:
  nanoon:
    external:
      name: traefik_nanoon

