version: '2'
services:

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    networks:
      - nanoon
    environment:
      - PGID=$NANOON_GID
      - PUID=$NANOON_UID
      - TZ=Europe/Paris
    volumes:
      - $NANOON_CONFIGDIR/transmission/:/config
      - $NANOON_FILESDIR/Transmission/:/downloads
      - $NANOON_FILESDIR/Transmission/watch/:/watch

    labels:
     - "traefik.frontend.rule=Host:$NANOON_TORRENT"
     - "traefik.port=9091"
     - "traefik.enable=true"

networks:
  nanoon:
    external:
      name: traefik_nanoon

