version: '2'

services:
    # Frontend
    web:
        image: jitsi/web
        restart: always
        container_name: jisti-web
        env_file: ../envs/jitsi/.env
        #ports:
            #- '${HTTP_PORT}:80'
            #- '${HTTPS_PORT}:443'
        volumes:
            - $NANOON_CONFIGDIR/jitsi/meet:/config
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - JICOFO_AUTH_USER
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - TZ
        networks:
            nanoon:
        labels:
          - "traefik.frontend.rule=Host:$NANOON_MEET"
          - "traefik.port=80"
          - "traefik.enable=true"


    # XMPP server
    prosody:
        image: jitsi/prosody
        restart: always
        env_file: ../envs/jitsi/.env
        container_name: prosody-web
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - $NANOON_CONFIGDIR/jitsi/prosody:/config
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JIGASI_XMPP_USER
            - JIGASI_XMPP_PASSWORD
            - TZ
        networks:
           nanoon:
                aliases:
                    - xmpp.meet.jitsi

    # Focus component
    jicofo:
        image: jitsi/jicofo
        restart: always
        env_file: ../envs/jitsi/.env
        container_name: jicofo
        volumes:
            - $NANOON_CONFIGDIR/jitsi/jicofo:/config
        environment:
            - ENABLE_AUTH
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER=xmpp.meet.jitsi
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JIGASI_BREWERY_MUC
            - TZ
        depends_on:
            - prosody
        networks:
            nanoon:

    # Video bridge
    jvb:
        image: jitsi/jvb
        restart: always
        env_file: ../envs/jitsi/.env
        container_name: jvb
        ports:
            - '10000/udp'
        volumes:
            - $NANOON_CONFIGDIR/jitsi/jvb:/config
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER=xmpp.meet.jitsi
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_PORT
            - JVB_STUN_SERVERS
            - JICOFO_AUTH_USER
            - TZ
        depends_on:
            - prosody
        networks:
            nanoon:

networks:
  nanoon:
    external:
      name: traefik_nanoon

