version: '2'
services:

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    networks:
      - nanoon
    environment:
      - PGID=100
      - PUID=1000
      - TZ=Europe/Paris
    volumes:
      - $NANOON_CONFIGDIR/transmission/:/config
      - $NANOON_FILESDIR/Transmission/:/downloads
      - $NANOON_FILESDIR/Transmission/watch/:/watch

    labels:
     - "traefik.frontend.rule=Host:$NANOON_TORRENT"
     - "traefik.port=9091"
     - "traefik.enable=true"

  pyload:
    image: writl/pyload
    container_name: pyload
    restart: always
    ports:
      - "9092:8000"
    networks:
      - nanoon
    environment:
      - PGID=100
      - PUID=1000
      - TZ=Europe/Paris
    volumes:
     - $NANOON_FILESDIR/Downloads/:/opt/pyload/Downloads
     - $NANOON_CONFIGDIR/pyload/:/opt/pyload/pyload-config
    labels:
     - "traefik.frontend.rule=Host:$NANOON_DOWNLOAD"
     - "traefik.port=8000"
     - "traefik.enable=true"

networks:
  nanoon:
    external:
      name: traefik_nanoon

